/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractGraph(targetPath: string): GraphData

export interface GraphData {
  nodes: Array<ReactFlowNode>
  edges: Array<ReactFlowEdge>
}

export interface ReactFlowEdge {
  id: string
  source: string
  target: string
}

export interface ReactFlowNode {
  id: string
  type: string
}
