/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CallEdgeData {
  calleeName: string
  kind: string
  confidence: string
  unresolved: boolean
}

export interface CallGraphData {
  nodes: Array<ReactFlowCallNode>
  edges: Array<ReactFlowCallEdge>
  issues: Array<CallGraphIssueData>
}

export interface CallGraphIssueData {
  id: string
  file: string
  kind: string
  message: string
}

export interface CallNodeData {
  label: string
  name: string
  file: string
  kind: string
  status: string
  spanStart: number
  spanEnd: number
  isEntry: boolean
}

export interface EdgeData {
  specifier: string
  isCircular: boolean
  unresolved: boolean
}

export declare function extractCallGraph(targetPath: string, entryFunction?: string | undefined | null): CallGraphData

export declare function extractGraph(targetPath: string): GraphData

export interface GraphData {
  nodes: Array<ReactFlowNode>
  edges: Array<ReactFlowEdge>
  issues: Array<GraphIssueData>
}

export interface GraphIssueData {
  id: string
  file: string
  kind: string
  message: string
}

export interface NodeData {
  label: string
  path: string
  kind: string
  status: string
  isEntry: boolean
}

export interface ReactFlowCallEdge {
  id: string
  source: string
  target: string
  data: CallEdgeData
}

export interface ReactFlowCallNode {
  id: string
  type: string
  data: CallNodeData
}

export interface ReactFlowEdge {
  id: string
  source: string
  target: string
  data: EdgeData
}

export interface ReactFlowNode {
  id: string
  type: string
  data: NodeData
}
