/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface EdgeData {
  specifier: string
  isCircular: boolean
  unresolved: boolean
}

export declare function extractGraph(targetPath: string): GraphData

export interface GraphData {
  nodes: Array<ReactFlowNode>
  edges: Array<ReactFlowEdge>
  issues: Array<GraphIssueData>
}

export interface GraphIssueData {
  id: string
  file: string
  kind: string
  message: string
}

export interface NodeData {
  label: string
  path: string
  kind: string
  status: string
  isEntry: boolean
}

export interface ReactFlowEdge {
  id: string
  source: string
  target: string
  data: EdgeData
}

export interface ReactFlowNode {
  id: string
  type: string
  data: NodeData
}
